POST https://localhost:7295/api/products
Content-Type:application/json

{
    "name":"Domates",
    "price": 14,
    "description":"Bla bla"
}

###
PUT https://localhost:7295/api/products
Content-Type:application/json

{
    "name":"Salatalýk"
}